DROP TRIGGER IF EXISTS trg_labels_tombstone ON labels;
DROP FUNCTION IF EXISTS notes_label_tombstone();
DROP TABLE IF EXISTS label_tombstones;
DROP TRIGGER IF EXISTS trg_labels_change_seq ON labels;
DROP FUNCTION IF EXISTS notes_bump_label_seq();
ALTER TABLE labels DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS label_change_seq;
DROP TRIGGER IF EXISTS trg_notebooks_tombstone ON notebooks;
DROP FUNCTION IF EXISTS notes_notebook_tombstone();
DROP TABLE IF EXISTS notebook_tombstones;
DROP TRIGGER IF EXISTS trg_notebooks_change_seq ON notebooks;
DROP FUNCTION IF EXISTS notes_bump_notebook_seq();
ALTER TABLE notebooks DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS notebook_change_seq;
DROP TRIGGER IF EXISTS trg_note_labels_bump ON note_labels;
DROP FUNCTION IF EXISTS notes_nl_bump_note();
DROP TRIGGER IF EXISTS trg_notes_tombstone ON notes;
DROP FUNCTION IF EXISTS notes_note_tombstone();
DROP TABLE IF EXISTS note_tombstones;
DROP TRIGGER IF EXISTS trg_notes_change_seq ON notes;
DROP FUNCTION IF EXISTS notes_bump_note_seq();
ALTER TABLE notes DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS note_change_seq;
